// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: demotester.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoTesterGetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DemoTesterGetInfoRequest) Reset() {
	*x = DemoTesterGetInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demotester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoTesterGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoTesterGetInfoRequest) ProtoMessage() {}

func (x *DemoTesterGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demotester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoTesterGetInfoRequest.ProtoReflect.Descriptor instead.
func (*DemoTesterGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_demotester_proto_rawDescGZIP(), []int{0}
}

func (x *DemoTesterGetInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DemoTesterGetInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DemoTesterGetInfoReply) Reset() {
	*x = DemoTesterGetInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demotester_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoTesterGetInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoTesterGetInfoReply) ProtoMessage() {}

func (x *DemoTesterGetInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demotester_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoTesterGetInfoReply.ProtoReflect.Descriptor instead.
func (*DemoTesterGetInfoReply) Descriptor() ([]byte, []int) {
	return file_demotester_proto_rawDescGZIP(), []int{1}
}

func (x *DemoTesterGetInfoReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DemoTesterGetInfoReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DemoTesterGetInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DemoTesterGetNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DemoTesterGetNameRequest) Reset() {
	*x = DemoTesterGetNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demotester_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoTesterGetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoTesterGetNameRequest) ProtoMessage() {}

func (x *DemoTesterGetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demotester_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoTesterGetNameRequest.ProtoReflect.Descriptor instead.
func (*DemoTesterGetNameRequest) Descriptor() ([]byte, []int) {
	return file_demotester_proto_rawDescGZIP(), []int{2}
}

func (x *DemoTesterGetNameRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DemoTesterGetNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DemoTesterGetNameReply) Reset() {
	*x = DemoTesterGetNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demotester_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoTesterGetNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoTesterGetNameReply) ProtoMessage() {}

func (x *DemoTesterGetNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_demotester_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoTesterGetNameReply.ProtoReflect.Descriptor instead.
func (*DemoTesterGetNameReply) Descriptor() ([]byte, []int) {
	return file_demotester_proto_rawDescGZIP(), []int{3}
}

func (x *DemoTesterGetNameReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DemoTesterGetNameReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_demotester_proto protoreflect.FileDescriptor

var file_demotester_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x2a, 0x0a, 0x18,
	0x44, 0x65, 0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x16, 0x44, 0x65, 0x6d, 0x6f,
	0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65,
	0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x16, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xb2, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x6d,
	0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65,
	0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x65, 0x72, 0x47,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demotester_proto_rawDescOnce sync.Once
	file_demotester_proto_rawDescData = file_demotester_proto_rawDesc
)

func file_demotester_proto_rawDescGZIP() []byte {
	file_demotester_proto_rawDescOnce.Do(func() {
		file_demotester_proto_rawDescData = protoimpl.X.CompressGZIP(file_demotester_proto_rawDescData)
	})
	return file_demotester_proto_rawDescData
}

var file_demotester_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_demotester_proto_goTypes = []interface{}{
	(*DemoTesterGetInfoRequest)(nil), // 0: grpcdemo.DemoTesterGetInfoRequest
	(*DemoTesterGetInfoReply)(nil),   // 1: grpcdemo.DemoTesterGetInfoReply
	(*DemoTesterGetNameRequest)(nil), // 2: grpcdemo.DemoTesterGetNameRequest
	(*DemoTesterGetNameReply)(nil),   // 3: grpcdemo.DemoTesterGetNameReply
}
var file_demotester_proto_depIdxs = []int32{
	0, // 0: grpcdemo.DemoTester.GetInfo:input_type -> grpcdemo.DemoTesterGetInfoRequest
	2, // 1: grpcdemo.DemoTester.GetName:input_type -> grpcdemo.DemoTesterGetNameRequest
	1, // 2: grpcdemo.DemoTester.GetInfo:output_type -> grpcdemo.DemoTesterGetInfoReply
	3, // 3: grpcdemo.DemoTester.GetName:output_type -> grpcdemo.DemoTesterGetNameReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demotester_proto_init() }
func file_demotester_proto_init() {
	if File_demotester_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demotester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoTesterGetInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demotester_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoTesterGetInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demotester_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoTesterGetNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demotester_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoTesterGetNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demotester_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demotester_proto_goTypes,
		DependencyIndexes: file_demotester_proto_depIdxs,
		MessageInfos:      file_demotester_proto_msgTypes,
	}.Build()
	File_demotester_proto = out.File
	file_demotester_proto_rawDesc = nil
	file_demotester_proto_goTypes = nil
	file_demotester_proto_depIdxs = nil
}
