// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemoBookClient is the client API for DemoBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemoBookClient interface {
	GetName(ctx context.Context, in *DemoBookRequest, opts ...grpc.CallOption) (*DemoBookReply, error)
}

type demoBookClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoBookClient(cc grpc.ClientConnInterface) DemoBookClient {
	return &demoBookClient{cc}
}

func (c *demoBookClient) GetName(ctx context.Context, in *DemoBookRequest, opts ...grpc.CallOption) (*DemoBookReply, error) {
	out := new(DemoBookReply)
	err := c.cc.Invoke(ctx, "/grpcdemo.DemoBook/GetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoBookServer is the server API for DemoBook service.
// All implementations must embed UnimplementedDemoBookServer
// for forward compatibility
type DemoBookServer interface {
	GetName(context.Context, *DemoBookRequest) (*DemoBookReply, error)
	mustEmbedUnimplementedDemoBookServer()
}

// UnimplementedDemoBookServer must be embedded to have forward compatible implementations.
type UnimplementedDemoBookServer struct {
}

func (UnimplementedDemoBookServer) GetName(context.Context, *DemoBookRequest) (*DemoBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetName not implemented")
}
func (UnimplementedDemoBookServer) mustEmbedUnimplementedDemoBookServer() {}

// UnsafeDemoBookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemoBookServer will
// result in compilation errors.
type UnsafeDemoBookServer interface {
	mustEmbedUnimplementedDemoBookServer()
}

func RegisterDemoBookServer(s grpc.ServiceRegistrar, srv DemoBookServer) {
	s.RegisterService(&DemoBook_ServiceDesc, srv)
}

func _DemoBook_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoBookServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdemo.DemoBook/GetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoBookServer).GetName(ctx, req.(*DemoBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DemoBook_ServiceDesc is the grpc.ServiceDesc for DemoBook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemoBook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdemo.DemoBook",
	HandlerType: (*DemoBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetName",
			Handler:    _DemoBook_GetName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demobook.proto",
}
