// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: demobook.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemoBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DemoBookRequest) Reset() {
	*x = DemoBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demobook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoBookRequest) ProtoMessage() {}

func (x *DemoBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demobook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoBookRequest.ProtoReflect.Descriptor instead.
func (*DemoBookRequest) Descriptor() ([]byte, []int) {
	return file_demobook_proto_rawDescGZIP(), []int{0}
}

func (x *DemoBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DemoBookReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DemoBookReply) Reset() {
	*x = DemoBookReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demobook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoBookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoBookReply) ProtoMessage() {}

func (x *DemoBookReply) ProtoReflect() protoreflect.Message {
	mi := &file_demobook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoBookReply.ProtoReflect.Descriptor instead.
func (*DemoBookReply) Descriptor() ([]byte, []int) {
	return file_demobook_proto_rawDescGZIP(), []int{1}
}

func (x *DemoBookReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_demobook_proto protoreflect.FileDescriptor

var file_demobook_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65,
	0x6d, 0x6f, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a,
	0x0d, 0x44, 0x65, 0x6d, 0x6f, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0x4b, 0x0a, 0x08, 0x44, 0x65, 0x6d, 0x6f, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x3f,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6d, 0x6f, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x44, 0x65, 0x6d, 0x6f, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_demobook_proto_rawDescOnce sync.Once
	file_demobook_proto_rawDescData = file_demobook_proto_rawDesc
)

func file_demobook_proto_rawDescGZIP() []byte {
	file_demobook_proto_rawDescOnce.Do(func() {
		file_demobook_proto_rawDescData = protoimpl.X.CompressGZIP(file_demobook_proto_rawDescData)
	})
	return file_demobook_proto_rawDescData
}

var file_demobook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demobook_proto_goTypes = []interface{}{
	(*DemoBookRequest)(nil), // 0: grpcdemo.DemoBookRequest
	(*DemoBookReply)(nil),   // 1: grpcdemo.DemoBookReply
}
var file_demobook_proto_depIdxs = []int32{
	0, // 0: grpcdemo.DemoBook.GetName:input_type -> grpcdemo.DemoBookRequest
	1, // 1: grpcdemo.DemoBook.GetName:output_type -> grpcdemo.DemoBookReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demobook_proto_init() }
func file_demobook_proto_init() {
	if File_demobook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demobook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demobook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoBookReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demobook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demobook_proto_goTypes,
		DependencyIndexes: file_demobook_proto_depIdxs,
		MessageInfos:      file_demobook_proto_msgTypes,
	}.Build()
	File_demobook_proto = out.File
	file_demobook_proto_rawDesc = nil
	file_demobook_proto_goTypes = nil
	file_demobook_proto_depIdxs = nil
}
